name: Generate AMS configuration doc

on:
  push:
    paths:
      - 'ref/ams-configuration.tmpl.md'
      - 'ref/ams-configuration.yaml'

jobs:
  run:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Markdown file
        run: python scripts/generate-ams-config.py