name: Generate and commit AMS configuration doc

on:
  push:
    branches:
      - 'testbranch'
    paths:
      - 'ref/ams-configuration.tmpl.md'
      - 'ref/ams-configuration.yaml'

jobs:
  run:
    name: Generate and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Markdown file
        run: python scripts/generate-ams-config.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Generate AMS configuration doc'
          add: 'ref/ams-configuration.md'